spring:
  config:
    activate:
      on-profile: serverDynamo
    import: "optional:configserver:http://10.1.1.173:9500/"
  cloud:
    config:
      name: nosql
      profile: dynamo

encrypt:
  key: EjelT7fFw6T4LHQEuwtU