spring:
  config:
    activate:
      on-profile: serverDynamo
    import: "optional:configserver:http://3.39.179.146:9500/"
  cloud:
    config:
      name: nosql
      profile: dynamo

encrypt:
  key: EjelT7fFw6T4LHQEuwtU